export interface IProduct {
  listing_id: number;
  state?: string;
  user_id?: number;
  category_id?: number;
  title?: string;
  description?: string;
  creation_tsz?: number;
  ending_tsz?: number;
  original_creation_tsz?: number;
  last_modified_tsz?: number;
  price?: string;
  currency_code?: string | undefined;
  quantity?: number;
  sku: SkyType[];
  tags?: TagsType[];
  category_path?: CategoryPathType[];
  category_path_ids?: CategoryPathIdsType[];
  materials?: MaterialsType[];
  shop_section_id?: number | null;
  featured_rank?: null | number;
  state_tsz?: number;
  url?: string;
  views?: number;
  num_favorers?: number;
  shipping_template_id?: null | number;
  processing_min?: number | null;
  processing_max?: number | null;
  who_made?: string;
  is_supply?: string;
  when_made?: string;
  item_weight?: null;
  item_weight_unit?: string;
  item_length?: null;
  item_width?: null;
  item_height?: null;
  item_dimensions_unit?: string;
  is_private?: boolean;
  recipient?: null | string;
  occasion?: null;
  style?: null | StyleType[];
  non_taxable?: boolean;
  is_customizable?: boolean;
  is_digital?: boolean;
  file_data?: string | undefined;
  should_auto_renew?: boolean;
  language?: string;
  has_variations?: boolean;
  taxonomy_id?: number;
  taxonomy_path?: TaxonomyPathType[];
  used_manufacturer?: boolean;
  MainImage?: {
    listing_image_id?: number;
    hex_code?: null;
    red?: null;
    green?: null;
    blue?: null;
    hue?: null;
    saturation?: null;
    brightness?: null;
    is_black_and_white?: null;
    creation_tsz?: null;
    listing_id?: number;
    rank?: null;
    url_75x75?: string;
    url_170x135?: string;
    url_570xN: string;
    url_fullxfull?: string;
    full_height?: null;
    full_width?: null;
    error_messages?: string;
  };
}

type SkyType = null | number | string;
type TagsType = string;
type CategoryPathType = string;
type CategoryPathIdsType = number;
type MaterialsType = string;
type TaxonomyPathType = string;
type StyleType = string;
